services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask_auth_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    # volumes:
    #   - /Users/SUPORTE POLIANA/OneDrive/Desktop/db